# Generated by Django 5.1.6 on 2025-02-10 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminhod',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminhod',
            name='name',
        ),
        migrations.RemoveField(
            model_name='adminhod',
            name='password',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='password',
        ),
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='password',
        ),
        migrations.AddField(
            model_name='students',
            name='admin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
